site1/app1/urls.py
from django.conf.urls import url, include
from django.views.generic import ListView
from django.views.generic.detail import DetailView

from . import models
from . import views

urlpatterns = [
    url(r'^listmusician/$', ListView.as_view(model=models.Musician),name='listmusician'),
    url(r'^detailmusician/(?P<pk>\d+)/$', DetailView.as_view(model=models.Musician),name='detailmusician'),
    url(r'^createmusician/$', views.MusicianCreate.as_view()),

    url(r'^detailalbum/(?P<pk>\d+)/$', DetailView.as_view(model=models.Album),name='detailalbum'),
    # Formmsets with Class based views
    url(r'^createalbum/$', views.AlbumCreate.as_view()),
    url(r'^editalbum/(?P<pk>\d+)$', views.AlbumEdit.as_view()),
    # regular formsets

]

site1/app2/urls.py
from django.conf.urls import url, include
from django.views.generic import ListView
from django.views.generic.detail import DetailView

from . import models
from . import views

urlpatterns = [
    url(r'^manage_books/$', views.manage_books,name='manage_books'),
    url(r'^manage_books/(?P<id_author>\d+)$', views.manage_books, name='manage_books_id_author'),
    url(r'^list$', ListView.as_view(model=models.Author),name='list'),
    # regular formsets
]

site1/site1/urls.py
from django.urls import include, path, re_path
from django.contrib import admin

from django.views.generic.base import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^app1/', include(('app1.urls', 'app1'), namespace='app1')),
    re_path(r'^app2/', include(('app2.urls', 'app2'), namespace='app2')),
    re_path(r'^app3/', include(('app3.urls', 'app3'), namespace='app3')),
    re_path(r'^$', RedirectView.as_view(pattern_name='app1:listmusician',
                                        permanent=False),
            name='index')
]

site1/app2/forms.py
from .models import Author, Book

from django.forms import ModelForm

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Field

class AuthorForm(ModelForm):
    def __init__(self, *args, **kwargs):
        self.helper = FormHelper()
        self.helper.form_tag = False
        self.helper.form_class = 'form-horizontal'
        super(AuthorForm, self).__init__(*args, **kwargs)
    class Meta:
        model = Author
        fields = '__all__'

class BookForm(ModelForm):
    def __init__(self, *args, **kwargs):
        self.helper = FormHelper()
        self.helper.form_tag = False
        self.helper.form_class = 'form-horizontal'
        super(BookForm, self).__init__(*args, **kwargs)

    class Meta:
        model = Book
        fields = '__all__'

site1/app2/views.py
from django.shortcuts import render, redirect, reverse
from .models import Author, Book
from .forms import AuthorForm, BookForm

from django.forms.models import inlineformset_factory

def manage_books(request, id_author=None):

    if id_author is None:
        # New
        author = Author()
        BookInlineFormSet = inlineformset_factory(Author, Book, form=BookForm, extra=3, can_delete=False)
    else:
        # Edit
        author = Author.objects.get(pk=id_author)
        BookInlineFormSet = inlineformset_factory(Author, Book, form=BookForm, extra=1, can_delete=True)


    if request.method == "POST":
        post_copy = request.POST.copy()
        if 'add_form' in request.POST:
            post_copy['nested-TOTAL_FORMS'] = int(post_copy['nested-TOTAL_FORMS'])+ 1

        form = AuthorForm(post_copy, request.FILES, instance=author, prefix="main")
        formset = BookInlineFormSet(post_copy, request.FILES, instance=author, prefix="nested")

        if 'add_form' not in request.POST and form.is_valid() and formset.is_valid():
            form.save()
            formset.save()
            return redirect(reverse('app2:list'))
    else:
        form = AuthorForm(instance=author, prefix="main")
        formset = BookInlineFormSet(instance=author, prefix="nested")

    return render(request, "app2/book_form.html", {"form":form, "formset": formset})

site1/templates/app2/author_list.html
{% extends "base.html" %}

{% block content %}
    <h2>Authors...</h2>
    <ul>
        {% for o in object_list %}
            <li><strong>Author: </strong>{{ o }} :: <a href="{% url 'app2:manage_books_id_author' o.id %}">Edit..</a></li>
              {% for b in o.books.all %}
              <p>
                {{b}}
              </p>
            {% endfor %}
        {% endfor %}
    </ul>

{% endblock %}

site1/templates/app2/book_form.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block content %}
    <h2>APP2: Create Album</h2>

    <form method="post" action="" class="form-horizontal">

      <h3>Author Form:</h3>
       {{ formset.management_form }}

       {% crispy form   %}

       <hr />
       <h3>Albuns Forms:</h3>
       <ul class="nav nav-tabs nav-justified">
       {% for f in formset %}
          <li class="{{ forloop.first|yesno:'active,'}}"><a data-toggle="tab" href="#tab{{forloop.counter}}">Tab {{forloop.counter}}</a>
          </li>
       {% endfor %}
      </ul>
      <div class="tab-content">
      {% for f in formset %}
          <div id="tab{{forloop.counter}}" class="tab-pane fade{{ forloop.first|yesno:' in active,'}}">
          {% crispy f f.helper %}
          </div>
       {% endfor %}
     </div>
     <hr />
     <button type="submit" class="btn btn-primary">Save</button>
     {% if form.first_name.value|length > 0 %}<button type="submit" name="add_form" class="btn btn-default">Add form...</button>{% endif %}

   </form>

{% endblock %}