site1/app1/urls.py
from django.conf.urls import url, include
from django.views.generic import ListView
from django.views.generic.detail import DetailView

from . import models
from . import views

urlpatterns = [
    url(r'^listmusician/$', ListView.as_view(model=models.Musician),name='listmusician'),
    url(r'^detailmusician/(?P<pk>\d+)/$', DetailView.as_view(model=models.Musician),name='detailmusician'),
    url(r'^createmusician/$', views.MusicianCreate.as_view()),

    url(r'^detailalbum/(?P<pk>\d+)/$', DetailView.as_view(model=models.Album),name='detailalbum'),
    # Formmsets with Class based views
    url(r'^createalbum/$', views.AlbumCreate.as_view()),
    url(r'^editalbum/(?P<pk>\d+)$', views.AlbumEdit.as_view()),
    # regular formsets

]

site1/app3/urls.py
from django.conf.urls import url, include
from django.views.generic import ListView
from django.views.generic.detail import DetailView

from . import models
from . import views

urlpatterns = [
    url(r'^$', ListView.as_view(model=models.Author),name='list'),
    # url(r'^/(?P<pk>\d+)$', DetailView.as_view(model=models.Author),name='detail'),
    url(r'^create/$', views.AuthorCreateView.as_view(),name='create'),
    url(r'^update/(?P<pk>\d+)$', views.AuthorUpdateView.as_view(),name='update'),


]

site1/site1/urls.py
from django.urls import include, path, re_path
from django.contrib import admin

from django.views.generic.base import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^app1/', include(('app1.urls', 'app1'), namespace='app1')),
    re_path(r'^app2/', include(('app2.urls', 'app2'), namespace='app2')),
    re_path(r'^app3/', include(('app3.urls', 'app3'), namespace='app3')),
    re_path(r'^$', RedirectView.as_view(pattern_name='app1:listmusician',
                                        permanent=False),
            name='index')
]

site1/app3/models.py
from django.db import models

# Create your models here.
class Author(models.Model):
    name = models.CharField(max_length=100)
    def __str__(self):
        return self.name

class Book(models.Model):
    author = models.ForeignKey(Author,
        on_delete=models.CASCADE,
        related_name="books",
        related_query_name="book")
    title = models.CharField(max_length=100)
    def __str__(self):
        return "{} :: {}".format(self.author, self.title)

site1/app3/forms.py
from .models import Author, Book

from django.forms import ModelForm
from django.forms.models import inlineformset_factory

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Field, HTML

class AuthorForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(AuthorForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = False
        self.helper.form_class = 'form-horizontal'
        self.helper.render_hidden_fields = True
    class Meta:
        model = Author
        fields = '__all__'

class BookForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(BookForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.form_tag = False
        self.helper.form_class = 'form-horizontal'
        self.helper.layout.append(HTML('<p>Some test html...</p>'))
        self.helper.render_hidden_fields = True

    class Meta:
        model = Book
        fields = '__all__'


# New
BookInlineFormSetCreate = inlineformset_factory(Author, Book, form=BookForm, extra=3, can_delete=False)
# Edit
BookInlineFormSetEdit = inlineformset_factory(Author, Book, form=BookForm, extra=1, can_delete=True)

site1/app3/views.py
from django.shortcuts import render, redirect, reverse
from .models import Author, Book
from .forms import AuthorForm, BookForm, BookInlineFormSetCreate, BookInlineFormSetEdit
from django.urls import reverse_lazy

from django.views.generic.edit import CreateView, UpdateView

from extra_views import InlineFormSet, CreateWithInlinesView, UpdateWithInlinesView
from extra_views.generic import GenericInlineFormSet

# See:
# https://django-extra-views.readthedocs.io/en/latest/index.html

class BookInlineFormSetCreate(InlineFormSet):
    model = Book
    form_class = BookForm
    fields = '__all__'
    extra = 3
    can_delete=False

class BookInlineFormSetUpdate(InlineFormSet):
    model = Book
    form_class = BookForm
    fields = '__all__'
    extra = 1
    can_delete=True

# Create your views here.
class AuthorCreateView(CreateWithInlinesView):
    form_class = AuthorForm
    inlines = [BookInlineFormSetCreate]
    model = Author
    #inline_model = Book
    success_url = reverse_lazy('app3:list')

# Create your views here.
class AuthorUpdateView(UpdateWithInlinesView):
    form_class = AuthorForm
    inlines = [BookInlineFormSetUpdate]
    model = Author
    success_url = reverse_lazy('app3:list')

site1/templates/app3/author_form.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block content %}
    <h2>Create Album</h2>

    {% load crispy_forms_tags %}
    <form method="post" action="" class="form-horizontal">

      <h3>Author Form:</h3>
       {% crispy form   %}

       {#% crispy formset formset.form.helper %#}

{% for formset in inlines %}

       {{ formset.management_form|crispy }}
       <hr />
       <h3>Albuns Forms:</h3>
       <ul class="nav nav-tabs nav-justified">

       {% for f in formset %}
          <li class="{{ forloop.first|yesno:'active,'}}"><a data-toggle="tab" href="#tab{{forloop.counter}}">Tab {{forloop.counter}}</a>
          </li>
       {% endfor %}
      </ul>
      <div class="tab-content">

      {% for f in formset %}
          <div id="tab{{forloop.counter}}" class="tab-pane fade{{ forloop.first|yesno:' in active,'}}">
          {% crispy f f.helper %}
          </div>
       {% endfor %}

{% endfor %}

     </div>
     <hr />
     <button type="submit" class="btn btn-primary">Save</button>
     {% if form.name.value|length > 0 %}<button type="submit" name="add_form" class="btn btn-default">Add form...</button>{% endif %}

   </form>

   {# <pre>{% debug %}</pre>#}

{% endblock %}

site1/templates/app3/author_list.html
{% extends "base.html" %}

{% block content %}
    <h2>Author list...</h2>
    <ul>
        {% for o in object_list %}
            <li><strong>Author: </strong>{{ o }} :: <a href="{% url 'app3:update' o.id %}">Edit..</a></li>
            {% for b in o.books.all %}
            <p>
              {{b}}
            </p>
          {% endfor %}
        {% endfor %}
    </ul>

{% endblock %}